### ISSUE TITLE
Controls Disabled for All Containers/VM's

### ISSUE THREAD

**Issue by jsquader** [dougiteixeira/proxmoxve#100]
Tried following the tutorial, along with help from [SmartHomeScene](https://smarthomescene.com/guides/how-to-monitor-and-control-proxmox-virtual-environment-in-home-assistant/). I am able to capture some of the data from my nodes, but it seems controls for any and all containers/vm's are still greyed out. I am currently using PVEAdmin for permissions group.

One other thing to mention is that I do have a cluster of 2 nodes currently. Not sure if this is the issue plaguing my setup.

Current instance for Proxmox is 7.4-3.

![Xnip2023-07-03_11-18-56](https://github.com/dougiteixeira/proxmoxve/assets/134555829/327a8af9-f7a7-4fa0-8ac4-19a71d89e95e)

**Comment by MistyMoose** [comment]
If you click on a control and open it, does it give you an option to "enable"?

**Comment by FelixMarschall** [comment]
I have the same issue. 

> If you click on a control and open it, does it give you an option to "enable"?

Does not work.

I did follow the [instructions](https://github.com/dougiteixeira/proxmoxve#readme) but cannot control the containers.

**Comment by dougiteixeira** [comment]
> I have the same issue.
> 
> > If you click on a control and open it, does it give you an option to "enable"?
> 
> Does not work.
> 
> I did follow the [instructions](https://github.com/dougiteixeira/proxmoxve#readme) but cannot control the containers.

Can you add a screenshot of the entity more information dialog which is not available?

**Comment by jsquader** [comment]
> If you click on a control and open it, does it give you an option to "enable"?

@MistyMoose brilliant proposal. Seems to have fixed my issues. Not sure why they're disabled by default while some of the other sensors are enabled by default. Basically went into the entities tab on my devices, filtered by my Proxmox instance and button, selected all and enabled them. Then I just restarted HAOS and BOOM! Everything is working as expected.

**Comment by dougiteixeira** [comment]
> Not sure why they're disabled by default while some of the other sensors are enabled by default.

They are disabled by default as they can be triggered improperly (there is no confirmation of the command), so each user activates the command that is most convenient for them.

### A step by step to enable entities:

1) Go to the page for the device you want to enable the pushbutton (or sensor).
![image](https://github.com/dougiteixeira/proxmoxve/assets/31328123/4e3f9b7d-e935-4fc5-bdd3-3329ef9b90a8)

2) Click +x entities not show
![image](https://github.com/dougiteixeira/proxmoxve/assets/31328123/0240d2ed-efac-4c59-9def-e721a44dde90)

3) Click on the entity you want to enable and click on settings (on the gear icon):
![image](https://github.com/dougiteixeira/proxmoxve/assets/31328123/e1bd2fb2-6fb5-4919-88c1-8056b7435f87)

4) Click the Enable button at the top of the dialog:
![image](https://github.com/dougiteixeira/proxmoxve/assets/31328123/1a8205e4-a779-4a01-922d-5d147e8e5766)

5) Wait a while (approximately 30 seconds) for the entity to be enabled. If you don't want to wait, just reload the configuration entry on the integration page.
![image](https://github.com/dougiteixeira/proxmoxve/assets/31328123/33edd547-8c55-44eb-b0b9-5036317bf077)

For the entity to appear enabled on the device page, it may be necessary to refresh the page.
