### ISSUE TITLE
Controls not available

### ISSUE THREAD

**Issue by jokerigno** [dougiteixeira/proxmoxve#126]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version.

### Describe the issue you are experiencing

I cannot see the buttons to act on VMs.

I followed the read me and I think permissions are ok.

![image](https://github.com/dougiteixeira/proxmoxve/assets/23552762/d5151bda-ed5f-402a-b6c7-dc4e20265632)

I can see sensor status but buttons are not available.

### In which version of Home Assistant Core do you have the problem?

Home Assistant 2023.7.3

### What version of Proxmox VE Custom Integration has the issue?

2.0.4

### Additional information

Proxmox version is: Virtual Environment 7.4-1

**Comment by dougiteixeira** [comment]
Please see https://github.com/dougiteixeira/proxmoxve/issues/100#issuecomment-1643042397
