### ISSUE TITLE
Integration fails to set up after 2023.8 update

### ISSUE THREAD

**Issue by Pivens** [dougiteixeira/proxmoxve#132]

**Comment by dougiteixeira** [comment]
> ### Checklist
> * [x]  I have updated to the latest available Proxmox VE Custom Integration version.

Please confirm that the Proxmox VE custom integration version is updated to the latest version 2.0.4.

From the logs it looks like you are running an old version of the custom integration.

**Comment by Pivens** [comment]
No...it seems that an old version interfered with my current installation....removed both....downloaded your new version, and everything is in alright now....Nonetheless, thank you very much for your quick response!
