### ISSUE TITLE
Interruptions in sensor data due to failed connections

### ISSUE THREAD

**Issue by mundschenk-at** [dougiteixeira/proxmoxve#133]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version.

### Describe the issue you are experiencing

HAOS is running a in Proxmox VM. I've noticed weird interruptions in the PVE uptime entities despite the uptime not changing. Looking more closely, I see intermittent connection errors in the logs. I am at a loss where these are coming from, the PVE host did not have any network interruptions since the last boot. The PVE host is using a custom CA (which HAOS knows about obviously). There are no errors in the `pveproxy` access log.

### In which version of Home Assistant Core do you have the problem?

core-2023.8.4

### What version of Proxmox VE Custom Integration has the issue?

2.0.4

### What version of Proxmox VE do you have the problem?

8.0.4

### Additional information

Here's an example (the API URLs and coordinator entities vary):

```
2023-09-04 21:55:42.107 ERROR (MainThread) [custom_components.proxmoxve] Error requesting proxmox_coordinator_<pvenode>:<port>_101 data: HTTPSConnectionPool(host='<pvenode>', port=<port>): Max retries exceeded with url: /api2/json/cluster/resources (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f34a5277a50>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by dougiteixeira** [comment]
Can you provide the debug logs? Include this in your config file:

```
logger:
  default: warning
  logs:
    custom_components.proxmoxve: debug
    proxmoxer: debug
```

After including this in your configuration file, restart Home Assistant, save the log file and send it here, please.

**Comment by dougiteixeira** [comment]
This issue is old and there was no feedback on the debug logs.

I will close it, if the problem persists in the latest version of the integration, please open a new issue.

**Comment by mundschenk-at** [comment]
Sorry, had it on my to do list for christmas but didn't get around. I'll open a new issue when I've collected the logs.
