### ISSUE TITLE
LXC Entities can't be customixed

### ISSUE THREAD

**Issue by Tux92** [dougiteixeira/proxmoxve#134]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version.

### Describe the issue you are experiencing

Entities sourced from LXC containers cannot be customized (name change, icon change, etc.). Customization works only in VM entities.

LXC Entities:
![image](https://github.com/dougiteixeira/proxmoxve/assets/26909922/f9865094-91b0-48c5-8707-b1c1103ec474)

VM Entities:
![image](https://github.com/dougiteixeira/proxmoxve/assets/26909922/01301c6a-420b-4d17-862d-4306a9d548bd)

### In which version of Home Assistant Core do you have the problem?

Home Assistant 2023.8.4 Frontend 20230802.1 - latest

### What version of Proxmox VE Custom Integration has the issue?

2.0.4

### What version of Proxmox VE do you have the problem?

8.0.3

**Comment by dougiteixeira** [comment]
This looks like a cache problem, can you clear the browser cache, refresh the page (CTRL + F5) and test again?

**Comment by Tux92** [comment]
Oh, you are right! Now all entities can be customized!
Thank you very much for your work.
