### ISSUE TITLE
Can't access node metrics, but can see containers/vms

### ISSUE THREAD

**Issue by ab3lson** [dougiteixeira/proxmoxve#135]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version.

### Describe the issue you are experiencing

I just set up the integration via HACs and am having a strange issue. I created a Proxmox user specifically for home assistant and gave it the Auditor permission. After I configured everything, I see this Error message 
`User hass@pve does not have sufficient permissions to access resource Node proxmox.`
I turned on debug messaging and don't see any other errors.

I verified that I am seeing statistics from my various VMs and LXCs that are running on Proxmox, so why would I not have permission to see what is running on the host? Is this a bug or a configuration issue on my end?

### In which version of Home Assistant Core do you have the problem?

2023.9.1

### What version of Proxmox VE Custom Integration has the issue?

2.0.4

### What version of Proxmox VE do you have the problem?

7.4-16

**Comment by dougiteixeira** [comment]
This permission is necessary for you to select the Node/VM/Container that will be exposed in the integration and for the sensor of the node that the VM/Container is running to work correctly. Ideally, the user should have this permission.

As this is not an integration issue, I will close this question, but feel free to ask for some support.
