### ISSUE TITLE
Suspending a VM doesn't change the status from "running"

### ISSUE THREAD

**Issue by colonelmattyman** [dougiteixeira/proxmoxve#137]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version.

### Describe the issue you are experiencing

Suspending a VM doesn't change the Status sensor from "Running".

It just changes the Health to "Problem".

Is it possible to get the status updated to "Running (Paused)" as it is in the Proxmox interface?

Proxmox
![image](https://github.com/dougiteixeira/proxmoxve/assets/12750307/37b22ee7-b82a-433e-a19e-8564cd372789)

Home Assistant
![image](https://github.com/dougiteixeira/proxmoxve/assets/12750307/4c4be0ac-8c57-478e-bd49-095e9f52da70)

### In which version of Home Assistant Core do you have the problem?

2023.9.3

### What version of Proxmox VE Custom Integration has the issue?

2.0.4

### What version of Proxmox VE do you have the problem?

7.2-3

**Comment by dougiteixeira** [comment]
The status binary sensor represents whether the VM/CT is running and for the Proxmox API the paused status is running.

To inform the paused status, a new status sensor was included (#163) that will represent the state of the VM/CT (Running, Stopped, Paused or another state not handled by the integration).
