### ISSUE TITLE
Integration needs reloading

### ISSUE THREAD

**Issue by rVlad93** [dougiteixeira/proxmoxve#139]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version.

### Describe the issue you are experiencing

Following setup :
Home Assistant running on a Rpi4
Proxmox running on an old PC

The integration works but if I power down the proxmox server and power it back on the integration needs reloading in order to get it to work again. Otherwise all the sensors and buttons are stuck in unavailable mode.

### In which version of Home Assistant Core do you have the problem?

2023.10.3

### What version of Proxmox VE Custom Integration has the issue?

2.0.4

### What version of Proxmox VE do you have the problem?

8.0.4

### Additional information

Only tested with this version so I have no idea if this was an issue before.

**Comment by dougiteixeira** [comment]
Duplicated with #93.
