### ISSUE TITLE
Promox loosing NIC after update to 3.0.0

### ISSUE THREAD

**Issue by amorozovs** [dougiteixeira/proxmoxve#169]
### Checklist

- [x] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Hi!
I updated integration from 2.0.6, that already had my promox box added) to the latest 3.0.0.
After that I restarted HA. After a full bootup I check the integration if VM harddrive size is reported. All the texts where missing, it showed the variables not text.
After that I checked if I can add a new entity, to my second promox. After opening the add new entity I closed the popup window.

After all this my proxmox box was not pinging. On my promox ve a have the OPNsense, HA, some other VMs and CTs. None of them was updating or any changes made.
Ping to the promox and opnsense did not go thru. After 50-100 seconds it was pinging for about 3-10 seconds. At that connection window I force stopped HA VM and disablet autostart. Did a proxmox reboot. Still had the issue. After stopping OPNSense VM the issue was gone. After OPNSense start, the issue was back. I did a full VM restore on OPNSense and HA, disabled the promox HA user and the system is now stable again.
OPNSense version: 23.7.8

### In which version of Home Assistant Core do you have the problem?

2023.11.1

### What version of Proxmox VE Custom Integration has the issue?

3.0.0

### What version of Proxmox VE do you have the problem?

8.0.3

**Comment by amorozovs** [comment]
Addition information
After less then 1h issue happened again. I started to check promox logs. Promox was loosing 1 of 4 NICs. All are Intel based. The NIC it was loosing is connected to HA. All other NICs have no issue. So that is not a driver issue.

Checked promox logs for past month, there was no issue with NICs.

Here is the log part from proxmox:
Nov 13 22:35:40 baseline kernel: igc 0000:04:00.0 enp4s0: NIC Link is Down
Nov 13 22:35:40 baseline kernel: vmbr1: port 1(enp4s0) entered disabled state
Nov 13 22:35:44 baseline kernel: igc 0000:04:00.0 enp4s0: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Nov 13 22:35:44 baseline kernel: vmbr1: port 1(enp4s0) entered blocking state
Nov 13 22:35:44 baseline kernel: vmbr1: port 1(enp4s0) entered forwarding state
Nov 13 22:35:45 baseline kernel: igc 0000:04:00.0 enp4s0: NIC Link is Down
Nov 13 22:35:45 baseline kernel: vmbr1: port 1(enp4s0) entered disabled state
Nov 13 22:35:48 baseline kernel: igc 0000:04:00.0 enp4s0: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Nov 13 22:35:48 baseline kernel: vmbr1: port 1(enp4s0) entered blocking state
Nov 13 22:35:48 baseline kernel: vmbr1: port 1(enp4s0) entered forwarding state

**Comment by dougiteixeira** [comment]
I don't see how custom integration could be related to this... and did you see something I missed?

**Comment by dougiteixeira** [comment]
Look this:
https://forum.proxmox.com/threads/nic-link-is-down-every-few-minutes.129210/

**Comment by amorozovs** [comment]
I have no idea. No other VM or CT or person has access to proxmox.
User I used had access to: PVEAdmin

**Comment by amorozovs** [comment]
Thanks for the link. There is no much info about this. There are problems with broadcom nics and proxmox, but this was Intels.
Tomorrow I will make full backups and try to recreate the same situation. I will post with my results.

Thanks for Your work with this integration!

**Comment by dougiteixeira** [comment]
> After stopping OPNSense VM the issue was gone. After OPNSense start, the issue was back.

Keeping the OpenSense VM stopped does the problem occur?

From your description, the issue is related to that VM and not the custom integration.

**Comment by amorozovs** [comment]
Yes, after OPNSense VM stopped the issue still exists. I traced it down to proxmox issue.

The problem started after I updated the integration to version 3.0, which has admin access to proxmox.

Still trying to pinpoint the roots of the issue. Maybe it was just a coincidence that after 2 minutes that I updated the HA integration issue started to happen. All night NIC was going down/up.

**Comment by barzag** [comment]
Good evening, I have exactly the same issue after updating Proxmox VE. Unable to ping the machine, and the GUI is unavailable. I performed a similar action for another problem, and Proxmox experienced regular disconnections, container interruptions, etc. Deleting groups and users resolved the issue on the other machine. However, for this one, I no longer have access to the GUI. Quite troublesome. Do you have any ideas on how to recover this home page?

**Comment by dougiteixeira** [comment]
Hi!

I don't see how integration could be impacting this.

Despite the permission being assigned to the integration user, there is no manipulation of nics by it, to confirm this just audit the integration code.

I would like to help, but I don't even know where to start, I still think it's more of a coincidence.

Do you have any evidence of this correlation?

There are many problems reported on the Proxmox forum that are similar, some very old and others more recent.

**Comment by amorozovs** [comment]
To wrap up everything.

Issue started with Proxmox started loosing one of the NICs, just after updating this integration.
Proxmox has this issue of loosing NICs and it very common with broadcom and realtek NICs. I have 4 Intel i226-V.

Proxmox was loosing one NIC in random times and random duration. After reading a lot of information on the internet, there was one suggestion, to test the Ethernet run. And yes, after 6 years of lifetime I re-terminated RJ45 and nor for 16h everything is stable. This network cable was untouched and was repluged for 2 month time. So it was not a suspect.

I hope this info helps to someone.

**Comment by amorozovs** [comment]
To wrap up everything.

Issue started with Proxmox started loosing one of the NICs, just after updating this integration.
Proxmox has this issue of loosing NICs and it very common with broadcom and realtek NICs. I have 4 Intel i226-V.

Proxmox was loosing one NIC in random times and random duration. After reading a lot of information on the internet, there was one suggestion, to test the Ethernet run. And yes, after 6 years of lifetime I re-terminated RJ45 and nor for 16h everything is stable. This network cable was untouched and was repluged for 2 month time. So it was not a suspect.

I hope this info helps to someone.

Big thanks to @dougiteixeira for creating this integration!
