### ISSUE TITLE
Error fetching Disk data: 'attributes' since version 3.2.0

### ISSUE THREAD

**Issue by nima-1102** [dougiteixeira/proxmoxve#181]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Since the last integration update there has been an error, the disk info is not updated or added.
Downgrading to version 3.1.0 fixed the problem for me.

```
Logger: custom_components.proxmoxve
Source: helpers/update_coordinator.py:290
Integration: Proxmox VE (documentation, issues)
First occurred: 22:42:21 (1 occurrences)
Last logged: 22:42:21

Unexpected error fetching proxmox_coordinator_disk_nuc_/dev/nvme0n1 data: 'attributes'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/coordinator.py", line 679, in _async_update_data
    for disk_attribute in disk_attributes_api["attributes"]:
                          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'attributes'

```

### In which version of Home Assistant Core do you have the problem?

2023.11.2

### What version of Proxmox VE Custom Integration has the issue?

3.2.0

### What version of Proxmox VE do you have the problem?

8.0.4

### Diagnostics information

[home-assistant_proxmoxve_2023-11-17T21-29-17.354Z.log](https://github.com/dougiteixeira/proxmoxve/files/13397734/home-assistant_proxmoxve_2023-11-17T21-29-17.354Z.log)

### Additional information

Proxmox has a single 2TB NVME SSD

**Comment by dougiteixeira** [comment]
This is caused by the way the API returns data from your Proxmox disks, it is returned in a text string instead of json.

I adjusted it to be compatible, please test version 3.2.1 and give feedback.

**Comment by nima-1102** [comment]
Works without any problems, thanks for the quick fix!
