### ISSUE TITLE
Proxmox drives not hibernating anymore

### ISSUE THREAD

**Issue by WhoTheHeck** [dougiteixeira/proxmoxve#188]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

One of my Proxmox nodes has a NAS VM where the HDDs are configured to hibernate when the VM is not running. Since v3.2.0 the disks are not hibernating anymore. I suppose this is due to the integration now regularly requesting the disk SMART states. Disabling the integration re-enables hibernating.

Can the integration be configured to not use the disk feature?
I removed the Datastore.Audit permission and also tried to disable the disk entities in HA. Both didnt help.
On the Proxmox node I run a script that checks if the disks are active first. Only if this is the case I check the SMART data.
`state=$(smartctl -i -n standby /dev/$drive | grep "ACTIVE or IDLE")`
Maybe there is a way that the integration also considers disk state.

### In which version of Home Assistant Core do you have the problem?

2023.11.3

### What version of Proxmox VE Custom Integration has the issue?

3.2.1

### What version of Proxmox VE do you have the problem?

8.0.4

### Diagnostics information

[config_entry-proxmoxve-aa0965641d6a455b5ef1946d2372f65c.json.txt](https://github.com/dougiteixeira/proxmoxve/files/13447026/config_entry-proxmoxve-aa0965641d6a455b5ef1946d2372f65c.json.txt)

**Comment by mauro-dasilva** [comment]
I had the same issue actually and disabled the HDD services. This allows the drives to Hibernate, but causes issues if the Proxmox VE integration restarts - https://github.com/dougiteixeira/proxmoxve/issues/190

**Comment by dougiteixeira** [comment]
I released version 3.2.2 which includes an integration configuration option to disable information about physical disks. I believe this solves this problem, can you test it and give feedback?

**Comment by WhoTheHeck** [comment]
Disks are hibernating again. Thanks for the quick fix, @dougiteixeira!
