### ISSUE TITLE
User not allowed to access the resource

### ISSUE THREAD

**Issue by duczz** [dougiteixeira/proxmoxve#200]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Logger: custom_components.proxmoxve
Source: helpers/update_coordinator.py:332
Integration: Proxmox VE (documentation, issues)
First occurred: 17:10:23 (1 occurrences)
Last logged: 17:10:23

Error fetching proxmox_coordinator_update_Proxmox data: User not allowed to access the resource, check user permissions as per the documentation, see details in the repair created by the integration.

### In which version of Home Assistant Core do you have the problem?

12.2023

### What version of Proxmox VE Custom Integration has the issue?

3.2.2

### What version of Proxmox VE do you have the problem?

3.2.2

### Additional information

Use Proxmox rights are PVEAudit

**Comment by danielholm** [comment]
Same issue here. I have several Proxmox instances and one of them gives me this issue. Same setup in terms of permissions.

**Comment by xPedion** [comment]
Same here. I also got the following notification:
```
User readonly does not have sufficient permissions to access resource Update myserver.

Tip on required permissions:

    ['perm','/nodes/myserver',['Sys.Modify']]

Please check documentation and user permissions.
```

When i remove the Node from the configuration and only monitor VM and QEMU, the problem disappears.

**Comment by MassiPi** [comment]
same here, i understand the Audit role should not be enough to trigger updates of the serve, but i'd expect to be able to see if any update is available..
![image](https://github.com/dougiteixeira/proxmoxve/assets/2384381/67176129-17a2-4b1e-acb6-c9d85e68c881)

**Comment by dougiteixeira** [comment]
To obtain information about updates, `Sys.Modify` permission is required. This is not defined by the integration but by the Proxmox API

**Comment by MassiPi** [comment]
Ok thank you this is clear. However, i disabled the 2 entities related with updates, but i still get the "Error fetching proxmox_coordinator_update_proxmox data: User not allowed to access the resource, check user permissions as per the documentation, see details in the repair created by the integration." at every reboot with my Audit profile user. Is this normal? This is not blocking anything, but i don't like having errors in my logs..
