### ISSUE TITLE
Temperature is reported as "Unknown" for Samsung 870 EVO 2.5" SATA SSD

### ISSUE THREAD

**Issue by swamytk** [dougiteixeira/proxmoxve#204]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

I have three NVMe SSDs, two SATA HDDs and two SATA 2.5" SSDs (Samsung 870 EVO) on Proxmox Server.  All temperature and health status are reported fine except both the Samsung 870 EVO. The temperature is reported as "Unknown". They are /dev/sda and /dev/sdb on this Server. 

![image](https://github.com/dougiteixeira/proxmoxve/assets/73037782/2ea7c891-6cba-4560-8a69-e987f7d07407)

### In which version of Home Assistant Core do you have the problem?

2023.12.3

### What version of Proxmox VE Custom Integration has the issue?

3.2.2

### What version of Proxmox VE do you have the problem?

pve-manager/8.1.3/b46aac3b42da5d15

### Diagnostics information

[proxmoxve-50e327dbb6f24f8b09602c7de6c0a832-Disk pve _dev_sdb-12b769616ff13cefa5542c5e0a870a91.json.txt](https://github.com/dougiteixeira/proxmoxve/files/13706495/proxmoxve-50e327dbb6f24f8b09602c7de6c0a832-Disk.pve._dev_sdb-12b769616ff13cefa5542c5e0a870a91.json.txt)

### Additional information
Update: I would like to add that Proxmox Web GUI reports the temperature properly. And also I was able to get temperature on command line using smartctl tool.
_No response_

**Comment by dougiteixeira** [comment]
According to the diagnostic file, this disk does not have temperature information (id 194 of the [S.M.A.R.T. attributes](https://en.wikipedia.org/wiki/Self-Monitoring,_Analysis_and_Reporting_Technology#Known_ATA_S.M.A.R.T._attributes)).

So there is nothing to do on the integration side.

**Comment by swamytk** [comment]
Thanks, @dougiteixeira for your time and effort . Now I notice these two SSDs are working fine but other two HDDs face same issues. 

Can you help me in diagnosing this? Since there is no agent deployed by this integration in Proxmox, I would like to know which library/tool get gather data from Proxmox? Any hint on such will help me to debug in my case?

**Comment by dougiteixeira** [comment]
@swamytk 

The best way to understand the behavior and the possibility of correction or addition of new features is by sending the integration diagnostic file, which will contain the information provided by the API for your instance.

The integration uses the [`proxmoxer` package](https://proxmoxer.github.io/docs/2.0/). The documentation on which the integration is based is that of the [Proxmox API](https://pve.proxmox.com/pve-docs/api-viewer/).

As for disk attributes, they should be standardized by the [S.M.A.R.T. specification](https://pt.m.wikipedia.org/wiki/S.M.A.R.T.), but manufacturers often implement them outside of it.

Regarding the temperature of your disk, in #239 (to be included in a future version) I included the Airflow Temperature sensor, which may be available for your disk, [the S.M.A.R.T. from Samsung is available here](https://download.semiconductor.samsung.com/resources/others/SSD_Application_Note_SMART_final.pdf).

I'm also thinking about including other useful information about disk health.
