### ISSUE TITLE
Disk Temperature Stucked

### ISSUE THREAD

**Issue by milandzuris** [dougiteixeira/proxmoxve#240]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Disk Temperature Stucked
![image](https://github.com/dougiteixeira/proxmoxve/assets/42905545/beb4732e-6d7b-4cb5-88f0-82c448d55d3a)

### In which version of Home Assistant Core do you have the problem?

*

### What version of Proxmox VE Custom Integration has the issue?

*

### What version of Proxmox VE do you have the problem?

*

**Comment by dougiteixeira** [comment]
Please enter the information requested by the issue form. Only then will I be able to analyze it.

In this specific case, please add screenshots of the Proxmox UI showing the temperature discrepancy and attach the diagnostic file for at least two instances when there is a temperature variation in the Proxmox UI.

I will close this issue, please create another one with the information above.
