### ISSUE TITLE
Reading incorrect RAM values

### ISSUE THREAD

**Issue by justcallmedudedude** [dougiteixeira/proxmoxve#251]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

For example, at this exact moment Proxmox is reporting 26.40GB used and 31.21GB available. However, the integration is reporting 28.33GB used and a total capacity of 33.52GB (calculated by adding the memory_free and memory_used values together).
![Screenshot 2024-01-10 193311](https://github.com/dougiteixeira/proxmoxve/assets/62908371/16bff7e0-b6b9-4933-aba1-065d048cbabf)
![Screenshot 2024-01-10 192836](https://github.com/dougiteixeira/proxmoxve/assets/62908371/d2f943b5-9d67-4764-ad14-061aa061e42d)

### In which version of Home Assistant Core do you have the problem?

2024.1.2

### What version of Proxmox VE Custom Integration has the issue?

3.3.0

### What version of Proxmox VE do you have the problem?

8.1.3

**Comment by dougiteixeira** [comment]
This seems to me to be just a [unit difference](https://massive.io/file-transfer/gb-vs-gib-whats-the-difference/)... please go to the memory entity configuration in Home Assistant, change the unit to GiB and compare the values.

**Comment by justcallmedudedude** [comment]
Oh wow do I feel silly. You are totally correct I completely missed the "i". After changing from GB to GiB all the values match.

**Comment by dougiteixeira** [comment]
> total capacity of 33.52GB (calculated by adding the memory_free and memory_used values together)

The integration has memory total sensor too, but it is disabled by default, if you want, just enable it.
