### ISSUE TITLE
Update Permissions

### ISSUE THREAD

**Issue by fotis3d** [dougiteixeira/proxmoxve#254]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

I keep getting the error below

![image](https://github.com/dougiteixeira/proxmoxve/assets/42974039/e4fa6d45-98d8-4bf7-be87-902824e3a330)

Even if I believe all the permission are correct in Proxmox

![image](https://github.com/dougiteixeira/proxmoxve/assets/42974039/4df520e7-c844-4a1a-8549-4e6e4567d2cb)

I have even disabled the update entities in HA but I still come up with this.

Do I miss something here ?

### In which version of Home Assistant Core do you have the problem?

2024.1.3

### What version of Proxmox VE Custom Integration has the issue?

3.3.0

### What version of Proxmox VE do you have the problem?

3.3.0

**Comment by dougiteixeira** [comment]
Can you show user/group permissions?

**Comment by fotis3d** [comment]
I think I got it. I needed to add the update permissions here. I hadn't done that.

![image](https://github.com/dougiteixeira/proxmoxve/assets/42974039/6c8d0497-0591-4a55-9f84-965f82a5e3a1)

thanks for your help and great effort :)

**Comment by dougiteixeira** [comment]
> I think I got it. I needed to add the update permissions here. I hadn't done that.
> 
> ![image](https://private-user-images.githubusercontent.com/42974039/297196446-6c8d0497-0591-4a55-9f84-965f82a5e3a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDIxOTksIm5iZiI6MTcwNTQ0MTg5OSwicGF0aCI6Ii80Mjk3NDAzOS8yOTcxOTY0NDYtNmM4ZDA0OTctMDU5MS00YTU1LTlmODQtOTY1ZjgyYTVlM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDIxNTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZmQ0ODI3MzNiMGRjMzU5OTViMjRkNjIwM2UxNzI4NWZkYWFhNjEwZDQ0ZjQxYzJmOGUwYzRkZTliZmIwZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sq_qq6ifOLL8J5Lzhqmw4oFxQfC8IyqhCLeYoFfGNvM)
> 
> thanks for your help and great effort :)

Ok, I'll close this, if you have any problems, create another issue.
