### ISSUE TITLE
HDD SDA and SDB sensor no longer available since version 3.4.0

### ISSUE THREAD

**Issue by werbi64** [dougiteixeira/proxmoxve#255]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

since version 3.4.0 the Disk sensors: /dev/sda and /dev/sdb are all "unavailable". If I put back version 3.3.0, they are new ok

### In which version of Home Assistant Core do you have the problem?

core - 2024.1.3

### What version of Proxmox VE Custom Integration has the issue?

Custom Integration version 3.4.0

### What version of Proxmox VE do you have the problem?

Proxmox VE 8.1.4

**Comment by dougiteixeira** [comment]
Please attach the integration [diagnostic file](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics).

**Comment by werbi64** [comment]
hello,
the diagnostic file
[config_entry-proxmoxve-a3640033057355bf60f315f8169a4fc1.json.txt](https://github.com/dougiteixeira/proxmoxve/files/13975441/config_entry-proxmoxve-a3640033057355bf60f315f8169a4fc1.json.txt)

**Comment by dougiteixeira** [comment]
Please do the following steps to generate a debug log file:
  * [Enable debugging for integration](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging)
  * Reload the integration configuration entry.
  * [Disable debugging and download the generated file](https://www.home-assistant.io/docs/configuration/troubleshooting/#disable-debug-logging-and-download-logs)

Send it here so you can get a clue about the problem.

**Comment by werbi64** [comment]
[home-assistant_proxmoxve_2024-01-20T16-13-48.653Z.log](https://github.com/dougiteixeira/proxmoxve/files/13998547/home-assistant_proxmoxve_2024-01-20T16-13-48.653Z.log)

**Comment by dougiteixeira** [comment]
Please download the `main` version of the integration and test if the issue is fixed.

If using HACS:
* Click Redownload
![IMG_2769](https://github.com/dougiteixeira/proxmoxve/assets/31328123/f0c24c50-09f6-4d39-975c-7c0217dc1ecd)
* Select the `main` version and click Download.
![IMG_2768](https://github.com/dougiteixeira/proxmoxve/assets/31328123/2fbb1066-e69b-4fe0-b59e-d13ea94c1658)

**Comment by werbi64** [comment]
👍

**Comment by to4ko** [comment]
not sure if this is connected, but 

having below error on 2024.1.3-4-5 with integration v3.4 as well as with "main" version


Logger: custom_components.proxmoxve
Source: helpers/update_coordinator.py:332
Integration: Proxmox VE ([documentation](https://github.com/dougiteixeira/proxmoxve), [issues](https://github.com/dougiteixeira/proxmoxve/issues))
First occurred: 00:36:13 (1 occurrences)
Last logged: 00:36:13

Error fetching proxmox_coordinator_disk_pmox01_/dev/sdb data:

**Comment by dougiteixeira** [comment]
> not sure if this is connected, but
> 
> having below error on 2024.1.3-4-5 with integration v3.4 as well as with "main" version
> 
> Logger: custom_components.proxmoxve Source: helpers/update_coordinator.py:332 Integration: Proxmox VE ([documentation](https://github.com/dougiteixeira/proxmoxve), [issues](https://github.com/dougiteixeira/proxmoxve/issues)) First occurred: 00:36:13 (1 occurrences) Last logged: 00:36:13
> 
> Error fetching proxmox_coordinator_disk_pmox01_/dev/sdb data:

@to4ko, I need the diagnostic files and debug logs to evaluate.

Please open a new issue and attach the files.
