### ISSUE TITLE
LXC not showing

### ISSUE THREAD

**Issue by duczz** [dougiteixeira/proxmoxve#264]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Currently i see only the QEMU VM but no LXC VM, is for that some extra Config nesesery?

### In which version of Home Assistant Core do you have the problem?

01.2024

### What version of Proxmox VE Custom Integration has the issue?

3.4.0

### What version of Proxmox VE do you have the problem?

7.4-17

### Diagnostics information

![image](https://github.com/dougiteixeira/proxmoxve/assets/25475385/e4b88260-7c0f-4c1c-b76a-076c2549d3ae)

rights:
![image](https://github.com/dougiteixeira/proxmoxve/assets/25475385/63352faf-66da-4837-b5ad-0dcb277ccb50)

**Comment by dougiteixeira** [comment]
You must add the diagnostic files as instructed in the issue form.

Please, you can follow the steps below:

* [Enable integration debugging](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging).
* Reload the integration configuration entry.
[Download a diagnostic file](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics).
* [Disable integration debugging and download the generated log file](https://www.home-assistant.io/docs/configuration/troubleshooting/#disable-debug-logging-and-download-logs).
* Attach the diagnostic file and the generated log file here.

You must also confirm that this HomeAssistant rule is assigned to the user/group you are using in the integration.

**Comment by duczz** [comment]
[home-assistant_proxmoxve_2024-01-24T13-37-16.537Z.log](https://github.com/dougiteixeira/proxmoxve/files/14039047/home-assistant_proxmoxve_2024-01-24T13-37-16.537Z.log)
[config_entry-proxmoxve-b528367f6c672464c3200e8af80f4c4f.json.txt](https://github.com/dougiteixeira/proxmoxve/files/14039048/config_entry-proxmoxve-b528367f6c672464c3200e8af80f4c4f.json.txt)
