### ISSUE TITLE
Used diskspace works for containers but not for VM

### ISSUE THREAD

**Issue by RobertoCravallo** [dougiteixeira/proxmoxve#273]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Used diskspace shows UNKNOWN for VM but works for Linux Containers (LXC)

### In which version of Home Assistant Core do you have the problem?

2024.2.3 also 2024.2.2 and 2024.2.1 

### What version of Proxmox VE Custom Integration has the issue?

3.4.0

### What version of Proxmox VE do you have the problem?

8.1.4

### Diagnostics information

[home-assistant_proxmoxve_2024-02-24T13-32-56.811Z.log](https://github.com/dougiteixeira/proxmoxve/files/14393003/home-assistant_proxmoxve_2024-02-24T13-32-56.811Z.log)

### Additional information

Thank you for a way cool tool!!!

**Comment by dougiteixeira** [comment]
See https://github.com/dougiteixeira/proxmoxve/issues/141
