### ISSUE TITLE
Current version needs reauthentication every time the Node was off

### ISSUE THREAD

**Issue by krangchen** [dougiteixeira/proxmoxve#280]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

In recent versions, including 3.4, my automations that start the server/node via ILO and then - depending on which automation I chose - start a choice of VMs worked flawlessly no matter if I had the Node not running for hours or days. But recently after updating to 3.4.1 (I thought it showed 3.4.2 recently?) HASS always asks me to resubmit the credentials once the Node has started and is recognized by the integration rendering my automations useless.

### In which version of Home Assistant Core do you have the problem?

Core-2024.2.1

### What version of Proxmox VE Custom Integration has the issue?

3.4.2

### What version of Proxmox VE do you have the problem?

8.1.4

**Comment by andreaconfa** [comment]
+1

**Comment by brian316** [comment]
if this error comes up can we run a job once to reauthenticate

**Comment by krangchen** [comment]
> if this error comes up can we run a job once to reauthenticate

I can do it by hand but again it breaks automation. I have looked at other integrations having (re)authentication issue where this is solved by upgrading the integration or settings outside the integration that caused it. Here, that is not the case and maybe I'm stupid but I don't know how to automate a reauth progress within HASS as the (successful) authentication is not an entity/state I target...?!
Or is it some setting I can change in pve user accounts that I'm not aware of?
Issue still persists with current HASS/proxmox/integration versions

**Comment by amasolov** [comment]
+1

**Comment by 001384** [comment]
me too

**Comment by dougiteixeira** [comment]
I believe that the use of authentication token implemented in https://github.com/dougiteixeira/proxmoxve/pull/343 solves this definitively.

Released in version 3.5.0
