### ISSUE TITLE
HDD Space not showing up

### ISSUE THREAD

**Issue by duczz** [dougiteixeira/proxmoxve#281]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Is it normal that the LXC/QEMU HDD Space will not be listed? (Only from the node)
![image](https://github.com/dougiteixeira/proxmoxve/assets/25475385/64c696eb-7ac4-4d0a-bced-e30a378d0097)

### In which version of Home Assistant Core do you have the problem?

2024.3.1

### What version of Proxmox VE Custom Integration has the issue?

3.4.1

### What version of Proxmox VE do you have the problem?

3.4.1

**Comment by dougiteixeira** [comment]
See https://github.com/dougiteixeira/proxmoxve/issues/141

**Comment by dougiteixeira** [comment]
See https://github.com/dougiteixeira/proxmoxve/issues/141
