### ISSUE TITLE
Storage Device switching between cluster nodes

### ISSUE THREAD

**Issue by Gydesen** [dougiteixeira/proxmoxve#294]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

I have local ZFS storage on multiple nodes in a cluster that shares the same name. I can only add one of them as a device in the integration configuration.

![image](https://github.com/dougiteixeira/proxmoxve/assets/9414729/58dfc247-97b3-40a8-b2cb-bda690da6140)

The device added to home assistant switches between nodes. Sometimes showing the storage in one node, sometimes showing info from another node.

![image](https://github.com/dougiteixeira/proxmoxve/assets/9414729/08b1b438-6433-4937-8887-ae5b93f44684)

 

### In which version of Home Assistant Core do you have the problem?

2024.5.2

### What version of Proxmox VE Custom Integration has the issue?

3.4.1

### What version of Proxmox VE do you have the problem?

8.2.2

**Comment by dougiteixeira** [comment]
I don't use clusters, so I don't have much experience with it...

The integration updates the sensor node by making a request to the host's resources and taking the information it reports. So I believe that the integration is using what Proxmox is making available.

If you send the diagnostic files I can show you the server's response with the information.
