### ISSUE TITLE
Can't add repository at HA

### ISSUE THREAD

**Issue by smtac** [dougiteixeira/proxmoxve#297]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Hello,

I have trying to install it at my Home Assistant, but bottom to at it falls. And add link in custom repository fail with this error message:
![Screenshot_20240518-211934~2](https://github.com/dougiteixeira/proxmoxve/assets/1488198/bc5b1e80-7bc9-4443-a976-137addfce0a0)

## System Information

version | core-2024.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 62.3 GB
disk_used | 26.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Cloudflared (5.1.9), Git pull (7.14.1), Let's Encrypt (5.0.18), ESPHome (2024.5.0), SNMP Sensor Server (1.3.4), Matter Server (6.0.0), Network UPS Tools (0.13.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21 novembre 2023 à 21:21
-- | --
current_recorder_run | 18 mai 2024 à 02:01
estimated_db_size | 3431.94 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

If necessary you can ask me more datas about this issue.

### In which version of Home Assistant Core do you have the problem?

Core-2024.5.4

### What version of Proxmox VE Custom Integration has the issue?

Install step on current version 

### What version of Proxmox VE do you have the problem?

8.2.2

### Diagnostics information

I have trying to install it at my Home Assistant, but bottom to at it falls. And add link in custom repository fail with this error message:
![Screenshot_20240518-211934~2](https://github.com/dougiteixeira/proxmoxve/assets/1488198/bc5b1e80-7bc9-4443-a976-137addfce0a0)

**Comment by dougiteixeira** [comment]
You are trying to add the Home Assistant Addons repository, but it must be added to the HACS custom repositories.
