### ISSUE TITLE
Wearout show 0% for all SSD

### ISSUE THREAD

**Issue by DieMetRik** [dougiteixeira/proxmoxve#310]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Thanks a lot for your job!
But wearout show 0% for all SSD
![image](https://github.com/dougiteixeira/proxmoxve/assets/31734768/1df214f4-6b60-41e5-83f9-67986a73f3fa)

Second issue: after the update, the version in the description has not changed 
![image](https://github.com/dougiteixeira/proxmoxve/assets/31734768/2de1d0b5-df07-4bd2-bda8-706d47e93afc)
I try to redownload from HACS, but anyway 3.4.1

### In which version of Home Assistant Core do you have the problem?

2024.05.04

### What version of Proxmox VE Custom Integration has the issue?

3.4.2

### What version of Proxmox VE do you have the problem?

8.2.2

### Diagnostics information

[home-assistant_proxmoxve_2024-05-21T11-01-36.121Z.log](https://github.com/dougiteixeira/proxmoxve/files/15388932/home-assistant_proxmoxve_2024-05-21T11-01-36.121Z.log)
[config_entry-proxmoxve-2a1d5d5310ba421fad0563dc30d9ba74.json](https://github.com/dougiteixeira/proxmoxve/files/15388934/config_entry-proxmoxve-2a1d5d5310ba421fad0563dc30d9ba74.json)

**Comment by FredericMa** [comment]
I've noticed the same issue.
The wearout of my disk is at 72% while the wearout sensor shows 0.72%.
It looks like the value needs to be multiplied by 100 to become percent.

Home Assistant:
![image](https://github.com/dougiteixeira/proxmoxve/assets/7840263/d891c166-49a3-4b09-b663-7fd4245dcf68)

Proxmox:
![image](https://github.com/dougiteixeira/proxmoxve/assets/7840263/b6143376-9a3f-4044-b84a-fb94c1a20718)

**Comment by DieMetRik** [comment]
i find problem line 467 in file sensor.py
```conversion_fn=lambda x: (100 - x) / 100 if x != UNDEFINED else None,```
I edit file in /config/custom_components/proxmoxve/sensor.py
delete __pycache__/sensor.cpython-312.pyc
Restart HA
Now all OK
![image](https://github.com/dougiteixeira/proxmoxve/assets/31734768/cd2f0fd6-612c-44fa-b620-6ae2f5d164ab)

**Comment by marcolino7** [comment]
Same here

![image](https://github.com/dougiteixeira/proxmoxve/assets/11460036/da43da73-efe3-4e81-88de-0c0f45a5d413)

![image](https://github.com/dougiteixeira/proxmoxve/assets/11460036/279222bf-3aa0-45f3-8190-afe6acfedd51)

Waiting for fix
Thanks
