### ISSUE TITLE
"Updates packages" becomes unavailable after updating PVE node.

### ISSUE THREAD

**Issue by FredericMa** [dougiteixeira/proxmoxve#311]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

The sensor is available when there are updates available on the PVE node.
Once I update the packages, the sensor becomes unavailable in HA.

![image](https://github.com/dougiteixeira/proxmoxve/assets/7840263/aa17f0a2-db98-4482-8a03-3fbedb48d8f2)

### In which version of Home Assistant Core do you have the problem?

2024.5.4

### What version of Proxmox VE Custom Integration has the issue?

3.4.2

### What version of Proxmox VE do you have the problem?

8.2.2

### Diagnostics information

If it is useful and if you can provide me an e-mail address I can send the log and diagnostics file too, I'm happy to do so.

**Comment by peter-ogden** [comment]
I am experiencing the same issue. I updated to Proxmox 8.2.2 and the binary sensor is now no longer available.

**Comment by digitall12** [comment]
Here the same. Updated to Proxmox 8.2.2 and there is this error:

Permissions error for `Update Update proxmox01`
User homeassistant does not have sufficient permissions to access resource Update Update proxmox01.

Tip on required permissions:

['perm','/nodes/Update proxmox01',['Sys.Modify']]

**Comment by peter-ogden** [comment]
> Here the same. Updated to Proxmox 8.2.2 and there is this error:
> 
> Permissions error for `Update Update proxmox01` User homeassistant does not have sufficient permissions to access resource Update Update proxmox01.
> 
> Tip on required permissions:
> 
> ['perm','/nodes/Update proxmox01',['Sys.Modify']]

Those required permissions are already mentioned in the docs.

**Comment by hume-github** [comment]
> Those required permissions are already mentioned in the docs.

Yes, right below "It is not necessary to include all of the permission roles below, this will depend on your use of the integration."  A person looking to have HASS monitor PVE in a purely read-only capacity is not going to think adding that permission is something they should do.

I don't blame the integration for this... it looks like something that needs to be addressed on Proxmox's side.  A note in the docs might be helpful, though.

**Comment by ncodee** [comment]
Any update on this please? thanks

**Comment by peter-ogden** [comment]
I've discovered that if I know there is an update available for Proxmox then go into the integration in Home Assistant and run "configure" again, then go into "Add or remove Nodes, VMs, Containers or Storages" and then click "Submit" and "Close" without making any changes, the "Updates Packages" again becomes available (at least until the next time Proxmox is restarted).

Of course, this defeats the purpose of the Binary Sensor to alert me that there are Proxmox updates waiting to be applied!

**Comment by Diegocampy** [comment]
same situation for me after update.
Versione: Proxmox 8.2.2
hacs integration Proxmox: 3.4.1 is not updable, i try to update to 3.4.2 but remain 3.4.1

**Comment by dougiteixeira** [comment]
@FredericMa , @Diegocampy, @peter-ogden 
Please, You must add the diagnostic files as instructed in the issue form.

Please, you can follow the steps below:

* [Enable integration debugging](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging).
* Reload the integration configuration entry.
[Download a diagnostic file](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics).
* [Disable integration debugging and download the generated log file](https://www.home-assistant.io/docs/configuration/troubleshooting/#disable-debug-logging-and-download-logs).
* Attach the diagnostic file and the generated log file here.

**Comment by FredericMa** [comment]
Sure, I'm happy to do so. That's why I asked if you can provide an email address to send it to when I created the issue. This is out of privacy concerns to not just put the file here in the issue.

**Comment by dougiteixeira** [comment]
> Sure, I'm happy to do so. That's why I asked if you can provide an email address to send it to when I created the issue. This is out of privacy concerns to not just put the file here in the issue.

On the integration side, all sensitive information (host, username, passwords, etc.) is suppressed. By the way, it is the standard used by the Home Assistant team.

**Comment by FredericMa** [comment]
I just prepared a log file but it's not necessary anymore I see. 😄 
Thanks a lot!

**Comment by ncodee** [comment]
@dougiteixeira Issue still persists in v3.4.4.
