### ISSUE TITLE
"Unexpected error" when trying to configure a PVE host

### ISSUE THREAD

**Issue by MrHaroldA** [dougiteixeira/proxmoxve#314]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

When trying to add my Proxmox VE server to HGA using this integration and all proviced instructions, I get an 'Unexpected error' in the add integration dialog.

![image](https://github.com/dougiteixeira/proxmoxve/assets/695291/f27107bd-fde9-40ca-aaf0-31a3e638a55f)

There's nothing relevant in the logs; enabling the debug logging for proxmoxve did not change anything.

### In which version of Home Assistant Core do you have the problem?

core-2024.5.5

### What version of Proxmox VE Custom Integration has the issue?

3.4.2

### What version of Proxmox VE do you have the problem?

8.2.2

**Comment by dougiteixeira** [comment]
In the host you must only enter the IP address, without https or forward slashes (/).
