### ISSUE TITLE
Question: how to add multiple Proxmox VE's to Home Assistant

### ISSUE THREAD

**Issue by tjzorro123** [dougiteixeira/proxmoxve#32]
Is it possible to add more than 1 Proxmox VE node to Home Assistant? If so, how can I configure that?

Thanks.

**Comment by dougiteixeira** [comment]
To add a new node to the Home Assistant integration, you must create a new configuration entry.

There are suggestions to change this is to allow adding in the same host config entry, but I haven't had time to work on that yet.
