### ISSUE TITLE
Storage reading issue when using integration with multiple nodes.

### ISSUE THREAD

**Issue by AsipecIT** [dougiteixeira/proxmoxve#321]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Disk is changing node every few minutes and sometimes is unavailable.
The HDD is 10TB but sometimes it shows the size 10Gb
And all of the sensors are affected and unit is in Gb
No errors in log.
Can i do something about it ?

Thank you all.

### In which version of Home Assistant Core do you have the problem?

2024.6.2

### What version of Proxmox VE Custom Integration has the issue?

3.4.1

### What version of Proxmox VE do you have the problem?

8.2.2

### Additional information

![image](https://github.com/dougiteixeira/proxmoxve/assets/149573885/4d73d72c-4ae4-4b1d-99c4-593781ce326a)

**Comment by dougiteixeira** [comment]
Fixes in #326.

**Comment by AsipecIT** [comment]
Than you. Testing for two days and it works without problem.
