### ISSUE TITLE
Wrong de.json contents in version 3.4.2

### ISSUE THREAD

**Issue by wolwin** [dougiteixeira/proxmoxve#322]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

The translation of the de.json file does not correspond to the 3.4.2 version.

### In which version of Home Assistant Core do you have the problem?

2024.6.3

### What version of Proxmox VE Custom Integration has the issue?

3.4.2

### What version of Proxmox VE do you have the problem?

8.2.2

### Additional information

Here the corrected de.json file for adoption:

[de_3.4.2.zip](https://github.com/user-attachments/files/15882342/de_3.4.2.zip)

**Comment by dougiteixeira** [comment]
I didn't understand what the problem was. I will close it.

Please, when you identify an error or issue in your native language translation files, please edit it and open a PR to update it.

I am unable to manage translations from all languages.
