### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ashoktvm** [dougiteixeira/proxmoxve#33]
Even after giving the correct username and pass it says invalid authentication

[
![image](https://user-images.githubusercontent.com/45116583/217771335-e55bed23-ab86-4910-a364-e4142de46600.png)
](url)

**Comment by dougiteixeira** [comment]
The `realm` for `root` user must be `pam` (Linux PAM standard authentication).

**Comment by ashoktvm** [comment]
Thanks. Is there anyway i can get the temperature value to HASS?

**Comment by dougiteixeira** [comment]
> Thanks. Is there any way i can get the temperature value to HASS?

By the Proxmox API there is no way.  I use a `cron` script that runs `xsensors` and publishes via the Home Assistant API.

**Comment by ashoktvm** [comment]
can you point to the direction on how to achieve this?
