### ISSUE TITLE
Removed the entity that displayed the disk used by local-lvm

### ISSUE THREAD

**Issue by TruantRiccardo** [dougiteixeira/proxmoxve#330]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Since the last update, there is no longer an entity that displays the disk usage of local-lvm. Only the disk usage of local and the VM usage are present. The VM usage is incorrect, fixed at 0%.

### In which version of Home Assistant Core do you have the problem?

2024.6.4

### What version of Proxmox VE Custom Integration has the issue?

3.4.3

### What version of Proxmox VE do you have the problem?

8.1.4

**Comment by dougiteixeira** [comment]
Some entities are disabled by default, just enable the entity you want: https://github.com/dougiteixeira/proxmoxve#some-entities-are-disabled-by-default-including-control-buttons-see-below-how-to-enable-them

About the VM showing 0% disk usage, see #141

**Comment by TruantRiccardo** [comment]
I have already activated all the disabled entities, but there is none related to local-lvm. Is this problem only mine? Regarding the 0% storage of the VM, the error is on the Proxmox side, not in the integration, sorry.

**Comment by dougiteixeira** [comment]
You must add the stores again through the integration config options.

**Comment by TruantRiccardo** [comment]
> You must add the stores again through the integration config options.

Solved, thank you. Completely forgotten about it.
