### ISSUE TITLE
Sys.modify authorization

### ISSUE THREAD

**Issue by vitofasano** [dougiteixeira/proxmoxve#334]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

When I restart Home Assistant I find this error message:

____
L'utente hass@pve non ha le autorizzazioni sufficienti per accedere alla risorsa {resource}.

Suggerimento sui permessi necessari:

    ['perm','/nodes/Update proxmox',['Sys.Modify']]

Si prega di consultare la documentazione e verificare le autorizzazioni dell'utente..
____

I close the error and it seems to work fine until the next restart of Home Assistant

<img width="910" alt="Screenshot 2024-07-07 alle 16 59 57" src="https://github.com/dougiteixeira/proxmoxve/assets/1392556/3b6c4139-b091-4dfe-b054-05550f099aba">

to configure proxmox within Home Assistant I followed the official guide, and until some time ago the error did not exist.

### In which version of Home Assistant Core do you have the problem?

2024.7.1

### What version of Proxmox VE Custom Integration has the issue?

3.4.4

### What version of Proxmox VE do you have the problem?

8.2.2

**Comment by MassiPi** [comment]
i can confirm.
honestly this is not the first update to the integration that toggles this kind of error, it would be nice to understand how to find out the specific access right that is rising the error. I definitely did not change anything and i'm not using HA to control proxmox, so i'm also quite curious :)

**Comment by oerix** [comment]
This has been a reoccurring issue for over 3 months now. At this point, feel like removing the integration all together.

**Comment by liakjim** [comment]
Reverting back to 3.4.2 and this issue is gone.

**Comment by Sab44** [comment]
I'm having the same issue. The documentation is lacking in that area, as it only says the permission is required to
>  Get information about available package updates to display on sensors
As far as I can see there is no sensor that would correlate to this in my entities list, so we can't disable it if we don't need it.

**Comment by xekil** [comment]
same error

**Comment by se4n01** [comment]
+1 but I did the workaround of adding the permission for my user in the roles section in proxmox UI

This may just be a documentation issue on the readme page, but would be good to know why this is needed in first place.

**Comment by xekil** [comment]
In my case I gave all the rights and I get this message each time I launch home assistant...

**Comment by scottcopus** [comment]
Is Sys.Modify a valid Proxmox VE permission anymore?

**Comment by MassiPi** [comment]
> I did the workaround of adding the permission for my user in the roles section in proxmox UI

sorry, but this is not a workaround. This is giving not needed permissions to a user. Simply wrong.

**Comment by dougiteixeira** [comment]
The Proxmox API requires this level of permission to access update information. We, as users, must accept or decline to use the feature that requires this permission.

There is nothing that can be done on the integration side.

**Comment by Sab44** [comment]
Hey @dougiteixeira thanks for coming back to this issue.
I wonder whether there has been a misunderstanding here.

To recap: we observe a HA repair issue telling us `User xxx@pve does not have sufficient permissions to access resource Update Update proxmox.`
* we, intentionally, did not grant this permission
* we, intentionally, choose not to fetch the update information from Proxmox

So all this is really about, is to get rid of that HA repair issue. It cannot be ignored permanently, it will keep popping up.
Please consider re-opening this and give us the possibility to opt-out of this functionality and make this repair issue disappear.
![Screenshot 2024-11-26 at 08 01 06](https://github.com/user-attachments/assets/21d16fe8-d28c-4dcc-955c-51ce52fb3640)

**Comment by MassiPi** [comment]
i second @Sab44 
we are not trying to get the integration to walk around proxmox security (lol), we are just saying we do not want to be forced to give modify permission to a user that, for our use, does not need it.
I do not need the modify permission. And also this was working in a previous version of the integration.

**Comment by MadWalnut** [comment]
@dougiteixeira Also supporting the point @Sab44 made. I do not need the permission and therefore have not granted it for security reasons. Everything works fine as is, it is just the repair popping up after every restart of Home Assistant that is annoying. Any chance to suppress it?
