### ISSUE TITLE
Storage does not exist - with permission

### ISSUE THREAD

**Issue by chicagoandy** [dougiteixeira/proxmoxve#335]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Getting errors on permissions for access filesystem.
![image](https://github.com/user-attachments/assets/77d6adfd-a579-4423-9d2e-a61e9f755472)

Role with permission is created: 
![image](https://github.com/user-attachments/assets/8e41ecbc-6d51-4bd5-9feb-af0dcf945b5f)

User has role:
![image](https://github.com/user-attachments/assets/e4b2e863-3804-435a-af7d-0f4b0ee62a89)

What am I missing...?

### In which version of Home Assistant Core do you have the problem?

core-2024.6.4

### What version of Proxmox VE Custom Integration has the issue?

3.4.4

### What version of Proxmox VE do you have the problem?

7.4

### Diagnostics information

[home-assistant_proxmoxve_2024-07-13T20-23-42.690Z.log](https://github.com/user-attachments/files/16203580/home-assistant_proxmoxve_2024-07-13T20-23-42.690Z.log)
[config_entry-proxmoxve-854f7a95cbf55c34318e7c21b95d76c0.json](https://github.com/user-attachments/files/16203582/config_entry-proxmoxve-854f7a95cbf55c34318e7c21b95d76c0.json)

**Comment by archit3kt** [comment]
Hello, I've got the same issue ! 

![image](https://github.com/user-attachments/assets/a4c38a23-3a9d-4e6d-ac52-d4090b188377)

Permissions are also set to Datastore.Audit, Sys.Audit, Sys.Modify, VM.Audit

Thank you for your help and great integration :)

**Comment by JuSchi89** [comment]
same issue here.

**Comment by MadWalnut** [comment]
Can confirm.

**Comment by SirJohnDoe** [comment]
Same issue here, 'local' and 'local-lvm' storage is not accessible even though 'Datastore.Audit' permission is added.

**Comment by SirJohnDoe** [comment]
I solved it by adding the standard role 'PVEAuditor'. So it seems that Mapping.Audit, Pool.Audit or SDN.audit permissions are necessary.

**Comment by vivdesign** [comment]
> Same here. Whatever permissions I give and even PVEAuditor the repair does not go away. Don't want to give admin as I just want to monitor.

same for me

**Comment by bearhntr** [comment]
I am getting 4 of these types of errors --- just for giggles (on this first PVE that I have added...I have 4 PVE total) - I changed the HomeAssistant from PVEAuditor to Admin - does not help.

![image](https://github.com/user-attachments/assets/6c7b7dc0-f1e4-4ece-a2a0-cb8241720651)

![image](https://github.com/user-attachments/assets/499c5a8a-1dd4-4202-9408-4ae923c2a099)

**Comment by bearhntr** [comment]
Update - after setting to PVEAdmin (in Proxmox) -- 4 of the errors disappeared after going back though  [ CONFIG ] under the Integration (was able to 'uncheck' storage items and 'check' the new ones 

![image](https://github.com/user-attachments/assets/02687e62-db74-41ae-9f7e-474ef4f77ed9)

... but now I have a new one.

![image](https://github.com/user-attachments/assets/d9efe135-325a-456d-a1d2-85b3d21c70fb)

**Comment by bearhntr** [comment]
2nd Update ---  I used these steps: https://github.com/dougiteixeira/proxmoxve#proxmox-permissions

  I created the 4 roles, and then added a 5th ` HomeAssistant.Admin ` that I put all of the permissions from the other 4 in this one.  I deleted the permissions setup, and added this one:
  
![image](https://github.com/user-attachments/assets/87109d78-b68a-4b5e-bc4b-a030ddd9c208)

Restarted HA - and all errors are gone.  

Now I get to play with what I can do with these things and make dashboards for PVE.  

** How long will the OLD Entities remain that were first created - is there a way to delete them? (or does this look about right for 1 (server with 2 vms) **

![image](https://github.com/user-attachments/assets/76e7f322-f7b5-472a-bfee-24ff00040e37)

**Comment by Johanneke** [comment]
@bearhntr you are a hero, this was the solution for me as well! Do not skip the step of removing the other permissions, that is crucial

**Comment by swa72** [comment]
Same error here, just to confirm

![image](https://github.com/user-attachments/assets/0841ec44-d933-4882-833f-19c29a36c79c)

with 

![image](https://github.com/user-attachments/assets/d860c9e7-d984-4aab-ac5c-54a613dd086b)

and the user

![image](https://github.com/user-attachments/assets/8164bc85-f8ff-458f-8509-1de816efbdac)

belongs to group

![image](https://github.com/user-attachments/assets/8b042948-6aec-4500-b4ee-4a01c89b7f62)

still, after reboot, results in ...

![image](https://github.com/user-attachments/assets/a27f65c5-293e-490f-acd8-b94683751e34)

**Comment by swa72** [comment]
Ok, found it. If you "configure" the integration again, you have to deselect the old entries and select the newly appeared entries. Got it.

**Comment by Hyrules** [comment]
Fixed it for me as well. This removed the old repairs.

**Comment by dougiteixeira** [comment]
> I used these steps: https://github.com/dougiteixeira/proxmoxve#proxmox-permissions
> 
> I created the 4 roles, and then added a 5th `HomeAssistant.Admin` that I put all of the permissions from the other 4 in this one. I deleted the permissions setup, and added this one:
> 
> ![image](https://private-user-images.githubusercontent.com/100164602/363243337-87109d78-b68a-4b5e-bc4b-a030ddd9c208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODY5NjYsIm5iZiI6MTczMjU4NjY2NiwicGF0aCI6Ii8xMDAxNjQ2MDIvMzYzMjQzMzM3LTg3MTA5ZDc4LWI2OGEtNGI1ZS1iYzRiLWEwMzBkZGQ5YzIwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMjA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWVhNWI2NDU0ZjkxZjBhODJiOTJjZGIwODc1YTgwODY3ZmRhYTVmNDY2NTQ0ZmM1ZDYyYmUwNjI3ZDczNzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._U-TZSyj96qJNWzAWldthdOLDGrTKY0yHWizqdw08Bc)
> 
> Restarted HA - and all errors are gone.

As confirmed here, when using the permissions as documented everything works, so there is no error on the integration side.

**Comment by chris400** [comment]
The issue still persists. Seems like the initial detection is slightly wrong.
This happened on 2 nodes for me.
See screenshots below.
It detected the storages _without_ pathname, but presents them afterwards with the pathname as additional options.
I have fixed this on the first node by simply unticking the wrong ones and ticking the right ones. I keep the wrong configuration on the second not to collect the screenshot.

Would you mind re-opening this issue or would you prefer a new issue? @dougiteixeira 

![Image](https://github.com/user-attachments/assets/5e8bd186-b7bc-4f41-88a4-fc561f5ac70d)

![Image](https://github.com/user-attachments/assets/6dc9f6d4-d7ea-47b3-a9cf-3ba0321b9c3d)

**Comment by dougiteixeira** [comment]
> The issue still persists. Seems like the initial detection is slightly wrong. This happened on 2 nodes for me. See screenshots below. It detected the storages _without_ pathname, but presents them afterwards with the pathname as additional options. I have fixed this on the first node by simply unticking the wrong ones and ticking the right ones. I keep the wrong configuration on the second not to collect the screenshot.
> 
> Would you mind re-opening this issue or would you prefer a new issue? [@dougiteixeira](https://github.com/dougiteixeira)
> 
> ![Image](https://github.com/user-attachments/assets/5e8bd186-b7bc-4f41-88a4-fc561f5ac70d)
> 
> ![Image](https://github.com/user-attachments/assets/6dc9f6d4-d7ea-47b3-a9cf-3ba0321b9c3d)

Open a new issue and attach the integration diagnostic file (as instructed in the issue form)
