### ISSUE TITLE
Proxmox 8.2.4 Configuration problem

### ISSUE THREAD

**Issue by dancm6** [dougiteixeira/proxmoxve#336]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Hello,

I have tried to configure it several times without success. I have created a user, group, and permissions correctly. I have modified the permissions to several options without being able to make it work. I don't know if it's because I'm using a recent version of Proxmox, I haven't been able to make it work.

I'm attaching the log of what it shows when I reload the component.

Thanks.

### In which version of Home Assistant Core do you have the problem?

2024.7.2

### What version of Proxmox VE Custom Integration has the issue?

3.4.4

### What version of Proxmox VE do you have the problem?

8.2.4

### Diagnostics information

![image](https://github.com/user-attachments/assets/e5d46adc-85dd-4e92-a92f-895f7eb2f7c1)
![image](https://github.com/user-attachments/assets/d16f7f8e-cb70-4cee-acf9-31e85fc3a5fe)
![image](https://github.com/user-attachments/assets/119b617f-1d65-4b7b-b689-520ef26515fc)

```
Registrador: homeassistant.config_entries
Fuente: config_entries.py:586
Ocurrió por primera vez: 13 de julio de 2024, 23:10:32 (16 ocurrencias)
Último inicio de sesión: 13:48:28

Error setting up entry 192.168.1.192:8006:8006 for proxmoxve
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/yarl/_url.py", line 191, in __new__
    port = val.port
           ^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as '8006:8006'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/__init__.py", line 584, in async_setup_entry
    device_info(
  File "/config/custom_components/proxmoxve/__init__.py", line 707, in device_info
    return device_registry.async_get_or_create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 702, in async_get_or_create
    configuration_url = _validate_configuration_url(configuration_url)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 266, in _validate_configuration_url
    url = value if type(value) is URL else _cached_parse_url(url_as_str)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yarl/_url.py", line 193, in __new__
    raise ValueError(
ValueError: Invalid URL: port can't be converted to integer
```

**Comment by dougiteixeira** [comment]
As reported in the logs and seen in the screenshots, the configured port is invalid (8006:8006). Correct this and test, if the errors persist, generate the integration diagnosis and open a new issue, attaching it according to the instructions in the additional information on the form.

**Comment by dancm6** [comment]
> As reported in the logs and seen in the screenshots, the configured port is invalid (8006:8006). Correct this and test, if the errors persist, generate the integration diagnosis and open a new issue, attaching it according to the instructions in the additional information on the form.

Thank you!

I hadn't seen it, I was configuring it wrong by putting the port in the access ip, that's why it was duplicated...sorry, I've been going crazy, thanks!
