### ISSUE TITLE
Time to update the info

### ISSUE THREAD

**Issue by rohoal1012** [dougiteixeira/proxmoxve#337]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

I noticed that the info in HA is updated every minute, i can change it to view it on real time?

### In which version of Home Assistant Core do you have the problem?

 2024.7.0

### What version of Proxmox VE Custom Integration has the issue?

latest

### What version of Proxmox VE do you have the problem?

 8.2.4

**Comment by DJMalachite** [comment]
Would also like this for more "realtime" monitoring

**Comment by dougiteixeira** [comment]
Just use the action to update, by setting up an automation you can work with the update rate you want.

```
action: homeassistant.update_entity
data:
  entity_id:
    - binary_sensor.node_pve_status
```
