### ISSUE TITLE
Integration won't load when missing VM ID

### ISSUE THREAD

**Issue by danielholm** [dougiteixeira/proxmoxve#34]
Hi,

Just found this integration, which indeed helps me more than the official proxmox ve integration in HA. Thank you.

I installed this custom integration and restarted HA. The previous settings form config.yml was imported successfully. However, one of my nodes did not load. I found that I had one machine ID in the HA config that was no longer available in PVE. When reconfiguring the integration, and I am presented with the list of available VM ID:s, the one no longer avaialble is of course not listed, but when trying to save, I get an error that the missing VM ID halts the save.

> User input malformed: 101 is not a valid option for dictionary value @ data['qemu']

I am unsure how to procees with removing the old VM ID. Also, could this be fixed by this integration by also listing, or even directly removing, missing VM ID:s?

**Comment by dougiteixeira** [comment]
I made a fix for this, can you try version 1.7.0 to see if it works for you?

**Comment by danielholm** [comment]
Worked like a charm! Error message as system notification and I was later able to uncheck the removed vm from the integration settings. Thank you so much. Great work
