### ISSUE TITLE
No way to enter token for token based auth

### ISSUE THREAD

**Issue by brettmiller** [dougiteixeira/proxmoxve#352]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Trying to setup the integration with token based authentication, which was added per issue #115 and PR #343. When adding the integration there are no token name and token secret fields only username and password. 

![proxmoxve-integration-setup](https://github.com/user-attachments/assets/181c6062-7cc5-4cd2-a727-3330ce38a2cd)

### In which version of Home Assistant Core do you have the problem?

2024.11.3

### What version of Proxmox VE Custom Integration has the issue?

3.4.4

### What version of Proxmox VE do you have the problem?

8.2.4

**Comment by dougiteixeira** [comment]
Released in version 3.5.0
