### ISSUE TITLE
No longer VM, disk and other and no possibility to select in config

### ISSUE THREAD

**Issue by webtoots** [dougiteixeira/proxmoxve#362]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

I no longer have any information or VM or disk since the update. There are surely things that were not specified in this update except the fact of having to reselect the VM, DISK and others
https://www.screenpresso.com/=V49EL0itL5Lw

### In which version of Home Assistant Core do you have the problem?

Core 2024.11.3

### What version of Proxmox VE Custom Integration has the issue?

3.5.0

### What version of Proxmox VE do you have the problem?

6.8.12-2

**Comment by asporykhin** [comment]
Same here.

HA: Core 2024.11.3
Proxmox VE Custom Integration: 3.5.0 and 3.5.1
Proxmox VE: 8.2.7

Currently downgraded to version 3.4.4 and things are back to normal.

**Comment by titis14** [comment]
Hi, same thing nothing works anymore here is what I have in the log.

`Error setting up entry 192.168.1.6:8006 for proxmoxve

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/__init__.py", line 349, in async_setup_entry
    token_name = entry_data[CONF_TOKEN_NAME]
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'token_name'`

**Comment by janfi67** [comment]
Same problem after 3.4.4 -> 3.5.0 upgrade

In which version of Home Assistant Core do you have the problem?
Core 2024.11.3

What version of Proxmox VE Custom Integration has the issue?
3.5.0

What version of Proxmox VE do you have the problem?
6.8.12-4

**Comment by titis14** [comment]
Go to configure and re-validate your identifiers without changing anything, that's good.

![firefox_2024-11-28_19-05-00](https://github.com/user-attachments/assets/8f809323-1a29-48b3-96ed-99682703d829)

**Comment by sabolcik** [comment]
I am experiencing the same issue.  Reloading the host authentication as highlighted above did not work for me.  Reverting to 3.5.0 worked for me.

**Comment by DevSecNinja** [comment]
> Hi, same thing nothing works anymore here is what I have in the log.
> 
> `Error setting up entry 192.168.1.6:8006 for proxmoxve
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/proxmoxve/**init**.py", line 349, in async_setup_entry token_name = entry_data[CONF_TOKEN_NAME] ~~~~~~~~~~^^^^^^^^^^^^^^^^^ KeyError: 'token_name'`

Same - after removing the integration I tried to re-add it but I can't re-add the integration anymore as it says 'Invalid authentication'.

**Comment by momonator25** [comment]
Had the same problem after updating from 3.4 to 3.5.1. and switching to token based auth.
Checking the permissions for the token in API Tokens Tab in Proxmox GUI: there were none.
Solved it by unchecking "Privilege Separation" for the created token for the integration. 
![proxmox-token](https://github.com/user-attachments/assets/b37e37e5-8da6-461a-93a3-31b2ec4751d0)

**Comment by webtoots** [comment]
Thank you very much @momonator25  ! It's working ! 
However, I have to redo my entire dashboard. :(

**Comment by momonator25** [comment]
> Thank you very much @momonator25 ! It's working ! However, I have to redo my entire dashboard. :(

Because you deleted the integration? If you used entities it should work if you name the new entity as the old one

**Comment by DevSecNinja** [comment]
> Can you clarify one point. The integration worked correctly with an empty token field in version 3.4.
> 
> Now with an empty token field the integration fails to load with the token error. I didn't change anything in my promox server to move to token based authentication.
> 
> Is this issue not a bug for those not using token authentication? The documentation change shows non-token authentication is still supported but it appears the integration fails with an empty token field.

Have you checked this one? https://github.com/dougiteixeira/proxmoxve/issues/362#issuecomment-2507206616

**Comment by sabolcik** [comment]
I tried reloading the integration without success and since I am not using
token authentication why would I need to change anything on the server?

Again the authentication worked using a password in 3.4 so I’m not sure why
the comment is relevant.  Can you clarify?

**Comment by dougiteixeira** [comment]
@sabolcik 
Please open a new issue and add the diagnostic and debug log file so we can understand your bug.

Please note that for not using
token authentication, you cannot fill in the token name field.

**Comment by dmizin37** [comment]
@momonator25 Thank you for sharing the fix for the token, got me up and running after hours of troubleshooting!
