### ISSUE TITLE
integration can't load

### ISSUE THREAD

**Issue by ChristophCaina** [dougiteixeira/proxmoxve#363]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

integration can't be loaded anymore.
I am getting the following error in the logs - no changes have been made in the config or the proxmox system:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/__init__.py", line 349, in async_setup_entry
    token_name = entry_data[CONF_TOKEN_NAME]
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'token_name'
```

any idea on how to solve this issue would be appreciated.
Thanks a lot :)

### In which version of Home Assistant Core do you have the problem?

2024.11.3

### What version of Proxmox VE Custom Integration has the issue?

3.5.1

### What version of Proxmox VE do you have the problem?

8.2.4

**Comment by jeansimeoni** [comment]
This solved it for me:
https://github.com/dougiteixeira/proxmoxve/issues/362#issuecomment-2506605219

**Comment by dougiteixeira** [comment]
Please, add the diagnostic and debug log file so we can understand your bug.

Please note that for not using
token authentication, you cannot fill in the token name field.

**Comment by remlei** [comment]
just add @pam on youbusername if your using proxmox authentication for that login.

**Comment by ChristophCaina** [comment]
this issue can be closed.
The recommendation from jeansimeoni did the trick :)
