### ISSUE TITLE
Version 3.5.2 no connection API Jeton

### ISSUE THREAD

**Issue by titis14** [dougiteixeira/proxmoxve#393]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Hello,
I just updated the integration to 3.5.2 but the integration no longer starts.
I recently switched to API Token I think I no longer have the problem following version 3.5.0.
I tried reconnecting and reloading the service but it still does not start the same.
HA has been rebooted completely and it is still the same.
In the logs it indicates unauthorized user except that it works well with the old version.
In terms of rights on the Token it is OK
![firefox_2024-12-10_21-05-22](https://github.com/user-attachments/assets/b72a2d68-2ef3-4f98-8253-54cbe388dd26)

Here is what I have in the logs:
```
Enregistreur: homeassistant.config_entries
Source: config_entries.py:635

Error setting up entry 192.168.1.6:8006 for proxmoxve
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/__init__.py", line 401, in async_setup_entry
    resources = await hass.async_add_executor_job(get_api, proxmox, "cluster/resources")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/api.py", line 91, in get_api
    api_result = proxmox.get(api_path)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/proxmoxer/core.py", line 169, in get
    return self(args)._request("GET", params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/proxmoxer/core.py", line 149, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 401 Unauthorized: no such user ('haproxmox@pve!haproxmox@pve') - {'errors': b''}
```

Thank you for your help.

### In which version of Home Assistant Core do you have the problem?

14

### What version of Proxmox VE Custom Integration has the issue?

3.5.2

### What version of Proxmox VE do you have the problem?

8.2.7

### Logs file

Enregistreur: homeassistant.config_entries
Source: config_entries.py:635

Error setting up entry 192.168.1.6:8006 for proxmoxve
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/__init__.py", line 401, in async_setup_entry
    resources = await hass.async_add_executor_job(get_api, proxmox, "cluster/resources")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/api.py", line 91, in get_api
    api_result = proxmox.get(api_path)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/proxmoxer/core.py", line 169, in get
    return self(args)._request("GET", params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/proxmoxer/core.py", line 149, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 401 Unauthorized: no such user ('haproxmox@pve!haproxmox@pve') - {'errors': b''}

### Diagnostics file

Unable to download

**Comment by titis14** [comment]
After several attempts at the login window I found the correct configuration.

**Comment by dougiteixeira** [comment]
> After several attempts at the login window I found the correct configuration.

Can you share where the error was so we can help more people and maybe handle the error in the integration?

**Comment by titis14** [comment]
I switched to token mode and I thought it was necessary to put the login of the full API token instead of user name.
It would be good to update the installation procedure with the new recommended method by adding the token creation and configuration part on HA.
![firefox_2024-12-10_23-03-42](https://github.com/user-attachments/assets/b28bfcf0-f8d0-4a2d-97a2-95a184b094a8)
Thanks for the work.
