### ISSUE TITLE
Cron email notification 

### ISSUE THREAD

**Issue by mousawm** [dougiteixeira/proxmoxve#417]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

I keep getting email notification from Proxmox whenever the sensor updated in home assistant.
How to change that ?

### In which version of Home Assistant Core do you have the problem?

2024.12.5

### What version of Proxmox VE Custom Integration has the issue?

3.5.2

### What version of Proxmox VE do you have the problem?

8.3.1

### Logs file

no need

### Diagnostics file

[config_entry-proxmoxve-01JCB641E3SBKS6MQ02KAMSW1K.json](https://github.com/user-attachments/files/18226092/config_entry-proxmoxve-01JCB641E3SBKS6MQ02KAMSW1K.json)

**Comment by dougiteixeira** [comment]
This does not seem to be related to the integration, but rather to your CRON configuration.

See more details at this link:
https://forum.proxmox.com/threads/disabling-crontab-mail-notifications.75663/
