### ISSUE TITLE
May I ask why the five items of information in the red frame of the picture are not displayed?

### ISSUE THREAD

**Issue by luckhy2882** [dougiteixeira/proxmoxve#43]
![ng](https://user-images.githubusercontent.com/125120787/224311145-415128ab-48d4-435f-8333-f4c3d2f9ca69.PNG)
May I ask why the five items of information in the red frame of the picture are not displayed?
It was caused by my setting error, thank you

**Comment by dougiteixeira** [comment]
These sensors are disabled by default, you can enable them in the configuration of each of the entities.
