### ISSUE TITLE
Sensors Remake

### ISSUE THREAD

**Issue by milandzuris** [dougiteixeira/proxmoxve#60]
1. Change Uptime time to minutes after minutes to hours after hours to days
2. Disk Used in % (no free)
3. Swap Used in %
4. Memory RAM Used in %

#EXAMPLE done Sensors in HA
CPU Used %
CPU Free %

RAM Used %
RAM Free%
RAM Used GB
RAM Free GB
RAM Total GB

DISK Used %
DISK Free %
DISK Used GB
DISK Free GB
DISK Total GB

SWAP Used %
SWAP Free %
SWAP Used GB
SWAP Free GB
SWAP Total GB

Sorry but you have big mess in Sensors, change mainly this Used GB to %, THX.

**Comment by dougiteixeira** [comment]
> 1. Change Uptime time to minutes after minutes to hours after hours to days

The uptime sensor has the TIMESTAMP device class, the frontend takes care of formatting the time. Besides that using an uptime sensor that is increasing is harmful to the database.
