### ISSUE TITLE
'Start' button on VM not available if VM is shutdown

### ISSUE THREAD

**Issue by suiciety** [dougiteixeira/proxmoxve#68]
I have a couple of VM's exposed and have noticed that when the vm is shutdown the Start button becomes unavailable which means you can't turn it back on.

Is there something I missed there?

Interestingly when I look a different VM that is shutdown that hasn't been powered on it does show the start button.

Thanks!

**Comment by suiciety** [comment]
![image](https://user-images.githubusercontent.com/8053509/232365946-e9fea765-991f-451c-9192-d461c9b2656a.png)

**Comment by dougiteixeira** [comment]
I have the impression from the screenshot that the button entities are disabled (they are created disabled by default), did you enable them?

After enabling them, you must wait a while for them to become active, but if you want to speed this up, just reload the integration.
