### ISSUE TITLE
No values in Used Space

### ISSUE THREAD

**Issue by AdmiralRaccoon** [dougiteixeira/proxmoxve#72]
Hello & thanks for the great integreation!
Everything works fine except the Disk sensors, every of my 4 VMs (Linux and Windows) shows "0.0" in used space. Do I have to configure them somehow?
I´m using Proxmox 7.4-3

Thank you,
Philipp

![image](https://user-images.githubusercontent.com/41727850/234029590-a82fa209-fa64-445e-a7ef-989065300457.png)

**Comment by AdmiralRaccoon** [comment]
Ok, found out that this is an proxmox issue and well known.

**Comment by dougiteixeira** [comment]
Are the values ​​shown in the Proxmox web interface like this too?  Or is there the correct data?

**Comment by AdmiralRaccoon** [comment]
Yes, they´re also at 0.0% in the web interface. I found this article to this issue: https://forum.proxmox.com/threads/vm-shows-0-0-disk-usage.114808/
