### ISSUE TITLE
Always needs re-authentication when started after longer time

### ISSUE THREAD

**Issue by Das-Suppenbrot** [dougiteixeira/proxmoxve#77]
I always have to re-authenticate the integration, after I started my Proxmox server. Maybe there is an automation for that?

**Comment by VeeeneX** [comment]
What do you see in the logs? In `<your-ha-host>/config/logs`?

**Comment by Das-Suppenbrot** [comment]
Today no request for authentication came up and nothing was in the logs. I saw no issues in the logs, maybe there was something faulty on my side. I'll keep an eye on it and report back if necessary.👍🏼

**Comment by dougiteixeira** [comment]
@Das-Suppenbrot Can you tell me if this behavior is still recurring?

**Comment by Das-Suppenbrot** [comment]
It seems to be fixed. Now it works just fine👍🏼.
Thanks for asking!

**Comment by VeeeneX** [comment]
Agree I had the similar problem and it's fixed now.
