### ISSUE TITLE
No sensor for local-zfs storage.. 

### ISSUE THREAD

**Issue by caublet** [dougiteixeira/proxmoxve#78]
I've just installed this integration through HACS. It's reporting properly all sensors from host and VMs. "Disk used pourcentage" is showing from "local" storage.. I'm only using "local-zfs" and can't find this metric. 

Any way around this?

**Comment by kaczkalolo** [comment]
I'm also looking for that...

**Comment by dougiteixeira** [comment]
Current disk sensors refer to VM/container disks.

The integration does not yet support storage sensors.

**Comment by dougiteixeira** [comment]
Duplicated with #28
