### ISSUE TITLE
Cant Connect to Proxmox

### ISSUE THREAD

**Issue by nasrulll** [dougiteixeira/proxmoxve#79]
Hello

i try to submit host information but still fail and can not connected

it said Invalid Authentication

thanks

**Comment by dougiteixeira** [comment]
Confirm the `realm` of the user you are trying to connect, you must type the same in the integration login screen (`pam` for Linux users and `pve` for Proxmox users...)

**Comment by djcrawleravp** [comment]
<img width="388" alt="Screen Shot 2024-01-11 at 19 29 40" src="https://github.com/dougiteixeira/proxmoxve/assets/12896341/6a1f5274-9d55-41af-9e49-39c9ec600cd6">


Same here :/
