### ISSUE TITLE
Disk free percentage

### ISSUE THREAD

**Issue by Veuchez** [dougiteixeira/proxmoxve#89]
I see Disk free percentage always at 100%. 
How come?
![image](https://github.com/dougiteixeira/proxmoxve/assets/59020055/01bbba8c-2c55-4c61-856b-2c94a211f7ad)

**Comment by dougiteixeira** [comment]
Look this: https://github.com/dougiteixeira/proxmoxve/issues/72#issuecomment-1521437249

It doesn't seem to be an integration issue.
