### ISSUE TITLE
Unverified HTTPS

### ISSUE THREAD

**Issue by andiukas** [dougiteixeira/proxmoxve#92]
Hi, how to repair this problem ? 

Logger: py.warnings
Source: custom_components/proxmoxve/coordinator.py:72
Integration: Proxmox VE ([documentation](https://github.com/dougiteixeira/proxmoxve), [issues](https://github.com/dougiteixeira/proxmoxve/issues))
First occurred: 09:45:37 (7 occurrences)
Last logged: 09:51:42

/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.3.12'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings warnings.warn(

**Comment by VeeeneX** [comment]
It's just a warning right?

**Comment by andiukas** [comment]
> It's just a warning right?

i think so, but there are maybe 7 messages and they keep repeating themselves

**Comment by SpartanTech** [comment]
started getting it too with the latest home assistant update. i have thousands of warnings in my log already increasing my IO time

**Comment by Bill-Dung** [comment]
Same here since HA Update 2013.6.0

**Comment by SpartanTech** [comment]
> Same here, after update to 2023.6.0
> 
> They are only warnings, but they are continuously spamming the log.

Yeah, io/disc usage is my main concern here. Even if we raise the log level or hide the warnings, it is still being written constantly, and a lot compared to everything else in the logs

**Comment by drthanwho** [comment]
ΗΑ shouldn't be logging those messages continuously in the first place too.

**Comment by elkarto** [comment]
I have added the proxmox CA certificate to my homeassistant, this way by checking the "Verify SSL" checkbox in the integration, it is able to validate the certificate and connect without any error or warning in the LOG.

**Comment by stncttr908** [comment]
> I have added the proxmox CA certificate to my homeassistant, this way by checking the "Verify SSL" checkbox in the integration, it is able to validate the certificate and connect without any error or warning in the LOG.

Any thoughts on how best to do this with the docker version of HA? Thanks!

**Comment by elkarto** [comment]
I have HAOS and have used this method:

https://community.home-assistant.io/t/let-home-assistant-trust-a-personal-certificate-authority/184917/22

I don't know if it will work in the docker version, I believe it does.

**Comment by snp88** [comment]
> > I have added the proxmox CA certificate to my homeassistant, this way by checking the "Verify SSL" checkbox in the integration, it is able to validate the certificate and connect without any error or warning in the LOG.
> 
> Any thoughts on how best to do this with the docker version of HA? Thanks!

Could you send me some instruction do do that ;)?

**Comment by stncttr908** [comment]
> I have HAOS and have used this method:
> 
> https://community.home-assistant.io/t/let-home-assistant-trust-a-personal-certificate-authority/184917/22
> 
> I don't know if it will work in the docker version, I believe it does.

It worked under docker just fine! Thank you!

**Comment by djdevil** [comment]
Hello everyone to solve the problem of the message in the logger here is a temporary fix!

[https://github.com/dougiteixeira/proxmoxve/pull/94](url)
