### ISSUE TITLE
Proxmox VE 8.0 upgrade issue - some entities are unavailable

### ISSUE THREAD

**Issue by Coder84619** [dougiteixeira/proxmoxve#99]
I upgraded two Proxmox VE 7.4 hosts to 8.0. However, there appears to be a compatibility issue. The old CPU/memory/swap/update  counters are unavailable. But a "fresh" set of counters are available and work. So I have to manually clean up the unavailable entities. Not sure if this is by design or not?

**Comment by jimbytes** [comment]
For me, it's not working at all.

**Comment by dougiteixeira** [comment]
Can you provide more information please:

* What version of the custom integration are you using?
* Are there any error messages in the logs regarding the Proxmox integration?
* After upgrading to Proxmox 8, did all entities stop working or were they replaced with new working entities?

**Comment by virtualben89** [comment]
I run into the same issue. It got it resolved by deleting all entities and devices, added the Proxmox host again and all machines and containers were recognized.

**Comment by dougiteixeira** [comment]
@Coder84619 and @virtualben89,

Can you provide more information please:

* What version of the custom integration are you using?
* Are there any error messages in the logs regarding the Proxmox integration?
* After upgrading to Proxmox 8, did all entities stop working or were they replaced with new working entities?

**Comment by dougiteixeira** [comment]
I understand this issue was caused by upgrading the integration to version 2.0.
I'm closing this soon, if you have more information, please open a new issue and attach the debug logs.
Thanks.
